- name: mukesh
  hosts: webserver
  tasks:
         - name: stop httpd
           service:
             name: httpd
             state: stopped
         - name: copy a file
           copy:
             src: /home/ansible/index.html
             dest: /var/www/html/  
           notify:
                Start httpd
  handlers:
       - name: Start httpd
         service:
           name: httpd
           state: started
